# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Heading(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Heading()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHeading(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Heading
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Heading
    def Angle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def HeadingStart(builder): builder.StartObject(1)
def Start(builder):
    return HeadingStart(builder)
def HeadingAddAngle(builder, angle): builder.PrependFloat64Slot(0, angle, 0.0)
def AddAngle(builder, angle):
    return HeadingAddAngle(builder, angle)
def HeadingEnd(builder): return builder.EndObject()
def End(builder):
    return HeadingEnd(builder)