# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

class KinematicQualityValue(object):
    kinematic_quality_value_none = 0
    kinematic_quality_value_bad = 1
    kinematic_quality_value_medium = 2
    kinematic_quality_value_good = 3
