# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class KinematicData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KinematicData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsKinematicData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # KinematicData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # KinematicData
    def Results(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from novatron_xsite3d_interface.fb.xcrtipcmsg.fb.KinematicDataResult import KinematicDataResult
            obj = KinematicDataResult()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KinematicData
    def ResultsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # KinematicData
    def ResultsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # KinematicData
    def QualityKinematics(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # KinematicData
    def MachineConfigChecksum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # KinematicData
    def RtkConfigChecksum(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # KinematicData
    def WorldOffset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = o + self._tab.Pos
            from novatron_xsite3d_interface.fb.xcrtipcmsg.fb.Vector3d import Vector3d
            obj = Vector3d()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KinematicData
    def TimestampUs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def KinematicDataStart(builder): builder.StartObject(6)
def Start(builder):
    return KinematicDataStart(builder)
def KinematicDataAddResults(builder, results): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(results), 0)
def AddResults(builder, results):
    return KinematicDataAddResults(builder, results)
def KinematicDataStartResultsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartResultsVector(builder, numElems):
    return KinematicDataStartResultsVector(builder, numElems)
def KinematicDataAddQualityKinematics(builder, qualityKinematics): builder.PrependUint32Slot(1, qualityKinematics, 0)
def AddQualityKinematics(builder, qualityKinematics):
    return KinematicDataAddQualityKinematics(builder, qualityKinematics)
def KinematicDataAddMachineConfigChecksum(builder, machineConfigChecksum): builder.PrependUint64Slot(2, machineConfigChecksum, 0)
def AddMachineConfigChecksum(builder, machineConfigChecksum):
    return KinematicDataAddMachineConfigChecksum(builder, machineConfigChecksum)
def KinematicDataAddRtkConfigChecksum(builder, rtkConfigChecksum): builder.PrependUint64Slot(3, rtkConfigChecksum, 0)
def AddRtkConfigChecksum(builder, rtkConfigChecksum):
    return KinematicDataAddRtkConfigChecksum(builder, rtkConfigChecksum)
def KinematicDataAddWorldOffset(builder, worldOffset): builder.PrependStructSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(worldOffset), 0)
def AddWorldOffset(builder, worldOffset):
    return KinematicDataAddWorldOffset(builder, worldOffset)
def KinematicDataAddTimestampUs(builder, timestampUs): builder.PrependUint64Slot(5, timestampUs, 0)
def AddTimestampUs(builder, timestampUs):
    return KinematicDataAddTimestampUs(builder, timestampUs)
def KinematicDataEnd(builder): return builder.EndObject()
def End(builder):
    return KinematicDataEnd(builder)