# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class KinematicDataResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KinematicDataResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsKinematicDataResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # KinematicDataResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # KinematicDataResult
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # KinematicDataResult
    def Origin(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from novatron_xsite3d_interface.fb.xcrtipcmsg.fb.Vector3 import Vector3
            obj = Vector3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KinematicDataResult
    def End(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from novatron_xsite3d_interface.fb.xcrtipcmsg.fb.Vector3 import Vector3
            obj = Vector3()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KinematicDataResult
    def Orientation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from novatron_xsite3d_interface.fb.xcrtipcmsg.fb.Quat import Quat
            obj = Quat()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # KinematicDataResult
    def Quality(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def KinematicDataResultStart(builder): builder.StartObject(5)
def Start(builder):
    return KinematicDataResultStart(builder)
def KinematicDataResultAddId(builder, id): builder.PrependInt16Slot(0, id, 0)
def AddId(builder, id):
    return KinematicDataResultAddId(builder, id)
def KinematicDataResultAddOrigin(builder, origin): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(origin), 0)
def AddOrigin(builder, origin):
    return KinematicDataResultAddOrigin(builder, origin)
def KinematicDataResultAddEnd(builder, end): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(end), 0)
def AddEnd(builder, end):
    return KinematicDataResultAddEnd(builder, end)
def KinematicDataResultAddOrientation(builder, orientation): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(orientation), 0)
def AddOrientation(builder, orientation):
    return KinematicDataResultAddOrientation(builder, orientation)
def KinematicDataResultAddQuality(builder, quality): builder.PrependUint32Slot(4, quality, 0)
def AddQuality(builder, quality):
    return KinematicDataResultAddQuality(builder, quality)
def KinematicDataResultEnd(builder): return builder.EndObject()
def End(builder):
    return KinematicDataResultEnd(builder)