# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Position(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Position()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPosition(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Position
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Position
    def Latitude(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Position
    def Longitude(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def PositionStart(builder): builder.StartObject(2)
def Start(builder):
    return PositionStart(builder)
def PositionAddLatitude(builder, latitude): builder.PrependFloat64Slot(0, latitude, 0.0)
def AddLatitude(builder, latitude):
    return PositionAddLatitude(builder, latitude)
def PositionAddLongitude(builder, longitude): builder.PrependFloat64Slot(1, longitude, 0.0)
def AddLongitude(builder, longitude):
    return PositionAddLongitude(builder, longitude)
def PositionEnd(builder): return builder.EndObject()
def End(builder):
    return PositionEnd(builder)