# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Scalar(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Scalar()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsScalar(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Scalar
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Scalar
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def ScalarStart(builder): builder.StartObject(1)
def Start(builder):
    return ScalarStart(builder)
def ScalarAddValue(builder, value): builder.PrependFloat64Slot(0, value, 0.0)
def AddValue(builder, value):
    return ScalarAddValue(builder, value)
def ScalarEnd(builder): return builder.EndObject()
def End(builder):
    return ScalarEnd(builder)